### ISSUE TITLE
Fatal NewGRF error for Stations & Waypoints 0.50

### ISSUE THREAD

**Issue by mxovd** [zephyris/opengfx2#111]
I get this error with OpenGFX NewGRF 0.5 upon loading a new game. I'm not sure if i'm doing something wrong.

Fatal: Unknown Action 0 property 0x1d (sprite 14)

- I'm using the steam version (13.4).
- The setting NewGRF and the base graphics were installed with the in-game content manager.
- The Hi-def graphics and the rest of the grf from the github releases.

![image](https://github.com/zephyris/opengfx2/assets/36765521/079306cb-27ef-496a-bb46-b4efc9f59345)

**Comment by zephyris** [comment]
Hi - sorry I forgot to reply to this sooner. The newGRF should work in vanilla 13.X OpenTTD, but due to a (highly technical) detail in how nmlc generates the newgrf it uses the Action0 property 0x1D when it doesn't need to. This should all be fixed in OpenTTD 14.0, so I'm planning to not worry about it and just update the compatibility requirement to be 14.0 or later.
