### ISSUE TITLE
Connection to zBase and project outlines?

### ISSUE THREAD

**Issue by buhtz** [zephyris/opengfx2#120]
I was pointed to that project while asking about the status of zBase (seems out dated).

Can you expand your README.md writing about how this project is connected to zBase.
It would also be nice to know (in the README.md) what are the plans for this project. It seems to be in development but is not available via the in-game downloader yet. So I assume it is kind of beta?

**Comment by zephyris** [comment]
It's totally separate to zBase... Totally separate sprite generation pipeline, totally separate code... And yup, zBase is dead - I've got no interest in keeping that going.

opengfx2 is on BaNaNaS, just search for opengfx2... The 4x zoom version isn't yet though, just because it is far from complete.

**Comment by buhtz** [comment]
opengfx2 is available via in-game downloader. But not the high res version.
What is bananas?

**Comment by zephyris** [comment]
BaNaNaS is the in-game content system. And, yup, the high res version isn't in it yet - it is far from complete and I don't want a partial/broken version in the system yet.
