### ISSUE TITLE
No OPENGFX2 settings

### ISSUE THREAD

**Issue by NeoFax75** [zephyris/opengfx2#20]
I followed the directions, and put the newgrf files into my newgrf folder, but there is no OPENGFX2 settings that shows up.  also, all of the other newgrfs that I have downloaded have a uuID-name folder and then the nml/lang folders.  should i create a similar structure?

**Comment by zephyris** [comment]
Hey, I think you have two problems. Firstly, the base set graphics should go in the baseset directory, not the newgrf directory. Secondly, you need to put the compiled baseset (in this case, the 6 grf files and the obg file, or simply the tar file containing all of these files) in the baseset directory. If you're seeing nml/laing files rather than grf files then it sounds like you're downloading source code rather than grfs...

**Comment by zephyris** [comment]
I'm hoping you've got this running, if you've still got issues then feel free to post again - ideally show a screenshot of the directory structure showing where you've put the files.

**Comment by youngwii2** [comment]
I am encountering the same issue with the OpenGFX2 settings being unavailable, even after selecting OGFX2 (both classic and EZ) as the base graphics. I have double checked to ensure that the correct files are in the correct places; screenshots attached.

I am using JGR's Patch Pack, at the latest version 0.54.5; I wonder if that might be the cause of my problem.

![OpenGFX2_BaseSet_Folder](https://github.com/zephyris/opengfx2/assets/52364182/87bd4768-825d-4c28-9967-a3ebc5ca8e91)
![OpenGFX2_Settings_NewGRF_Folder_Highlighted](https://github.com/zephyris/opengfx2/assets/52364182/6a9469cc-1444-4be8-bd59-896d85ee98ae)

**Comment by zephyris** [comment]
Ah, sorry, yeah - that must have caused a GRFID clash. Glad you got it resolved.
