### ISSUE TITLE
PBS signals use OpenGFX graphics assets in v0.1-beta

### ISSUE THREAD

**Issue by j-n-dev** [zephyris/opengfx2#21]
v0.1-alpha
![image](https://github.com/zephyris/opengfx2/assets/46166499/7c7888c3-b394-491b-8eff-db9b83322bc3)
v0.1-beta
![image](https://github.com/zephyris/opengfx2/assets/46166499/8b73297d-6b51-4803-bdde-1010ae05817e)
Tried modifying game settings to no avail. Issue affects both standard OpenTTD and JGR's patch. Not sure if this is intentional or not because I personally dislike how OpenGFX electric path signal graphics look when placed on orthogonal track.

**Comment by zephyris** [comment]
This was originally an overlooked bug - the intent was to use OpenGFX path signals but due to a coding error there was an invisible fallback to the built-in original graphics-like signals. So the v0.1 beta is "correct". Revisiting signals is on the to-do list, but likely will only be tackled when extra zoom sprites are added...

Could you add a screenshot of what you don't like about the OpenGFX-style sprites so I can take a look?
