### ISSUE TITLE
Should canals be company-coloured?

### ISSUE THREAD

**Issue by 2TallTyler** [zephyris/opengfx2#42]
![company-colour](https://github.com/zephyris/opengfx2/assets/55058389/9003b093-e08d-4bbd-b2ef-eb8488a2170c)

Canals appear to have a sign on the banks, which to me looks like the CC1 index colour, but it doesn't get recoloured accordingly (I am yellow, as seen on the track fences and airport).

If they're not supposed to be CC1, just close this. 😄

**Comment by zephyris** [comment]
IIRC this is a failed experiment. Canals (similar to roads, the other sharable infrastructure type) do not get recoloured using CC. Should be a relatively easy to patch OpenTTD to get it supported though... I'll leave it open for now, because stray blue does look a bit ugly.

More broadly, more recolouring would be nice. In particular 2CC recolouring of stations, depots, airports, HQs, etc. However, digging into the OpenTTD code that looks non-trivial.
