### ISSUE TITLE
Coal mine, gold mine and copper mine textures flicker where they shouldn't flicker. 

### ISSUE THREAD

**Issue by Rapha493** [zephyris/opengfx2#49]
Instead of only the wires to move, the buildings with the wires also tend to flicker a lot. The diamond mine doesn't move at all.

**Comment by DefinitelyNotRau117** [comment]
I wouldn't call it flickering, definitely not like #30, more like just animation artifacts.


This also appears on Oil Wells, but to a lesser extent. On the corner of gray box, around the support

https://github.com/zephyris/opengfx2/assets/115672237/5434aade-6b89-4d00-8a22-e24efd0ebb49

https://github.com/zephyris/opengfx2/assets/115672237/68a0da81-8ce7-470c-b661-16c3e6239735

https://github.com/zephyris/opengfx2/assets/115672237/94578b42-f776-4c14-92ac-8d85b4236021

https://github.com/zephyris/opengfx2/assets/115672237/1b676e74-2f10-4332-b38b-2b5fd6d79c2a

In addition, the animation of the plastic fountains extends slightly beyond the pool. And if you need to redo the animation to fix the corner, I would suggest making the color of the plastic more creamy than brown, now it looks more like chocolate than plastic.

https://github.com/zephyris/opengfx2/assets/115672237/e29d4e2b-3a10-49f4-90bd-30f46dc51d32



The diamond mine does not move in the normal baseset either. Perhaps it’s worth just removing the cable shaft so that it doesn’t look like a bug.

**Comment by zephyris** [comment]
This is what I was referring to in #25 (though this explains it more clearly!). I'll close this as a duplicate.
