### ISSUE TITLE
Weird water texture issue on a boat occupied square in FIRS (sorry if it's not the graphics problem)

### ISSUE THREAD

**Issue by Rapha493** [zephyris/opengfx2#58]
![Screenshot_2023-10-22-21-33-42-035_org openttd sdl](https://github.com/zephyris/opengfx2/assets/145707519/2b31c164-4751-461e-85a0-5b443789fbe6)

**Comment by zephyris** [comment]
I'd argue this is a FIRS bug... The cause of the issue is that the default water sprite tiles uses a select few non-animated pixels to reduce flicker when you zoom out. The closest non-animated match to the animated colours happen to be the company colour palette entries. FIRS applies recolour to a sprite set which reuses the water sprite, and applies the company colour recolour to it. The argument is that GRFs shouldn't assume it can apply recolours to base set sprites that it has no control over...

**Comment by zephyris** [comment]
There is a base set solution that looks identical. For the flat water tile, make a 32bpp sprite which is entirely r, g, b =128 except for the non-animated blue pixels, which should be the blue r, g, b. Then, an 8bpp mask which has just the animated pixels, and transparent blue elsewhere.
