### ISSUE TITLE
Bug: On regular rails, bridge ramps are not painted the color of the bridge itself

### ISSUE THREAD

**Issue by DefinitelyNotRau117** [zephyris/opengfx2#80]
On the maglev/monorail bridge ramps is colored correctly (except few pixels).
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/279d5d79-2466-4471-9907-ffddd6998073)

On regular rails, all ramps are the same color (Same thing in Toyland)
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/75faadff-218a-49c3-82b1-9c1ce4f21416)

Toyland steel gridger bridges have the wrong color on any rail type.
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/5b9b282b-4e6f-495a-b31a-c17ec2d8eff0)

Some pixels are not colored at all
![изображение](https://github.com/zephyris/opengfx2/assets/115672237/c20b5899-6944-4209-9988-82689181c672)

**Comment by zephyris** [comment]
Huh. Interesting one. Looks like two issues here:

One is a 32bpp->8bpp conversion mangling the bridge pixel indices. They get combined with the infrastructure/bridge decks in 32bpp which leads to dithering away from the correct indices when converted back to 8bpp. Dithering goes from top right to bottom left, so pixels to the bottom right of the road/rail/monorail will go wrong.

Second is that not all bridge ramps are recoloured... In the original graphics, in non-toyland, rail ramps are gray rather than red/brown, and red/brown are used for recolouring. I'll need to check the OTTD source, but I suspect they're simply not recoloured. Similarly, original graphics toyland bridge ramps for road/rail/maglev/monorail are all gray - and probably not remapped at all.

So, will take some thought on how to best handle all of this.

**Comment by zephyris** [comment]
Actually quite simple, just took some time to work out. Rail ramps aren't recoloured, so use gray/silver for those, and leave the others to recolour. And fix the missing recolour index protection/palmasking.
