### ISSUE TITLE
Buildings with concrete ground on Sub-Arctic above the snow line don't have snow on them

### ISSUE THREAD

**Issue by Rapha493** [zephyris/opengfx2#95]
(can't upload a screenshot for some reason) Basically on every town above the snowline on Sub-Arctic buildings with concrete as their ground should have some white on them to make them blend.
Also, kinda related to this, roads should also have a bit of a snow texture.

**Comment by zephyris** [comment]
This isn't fixable, at least not well. This is down to some peculiarities of how the base set graphics work. Above the snowline, many buildings still use the general town concrete tile, for example 4575, 4576, 4577, 4569, etc. That makes it impossible for those to have any snow on the ground tile. Some, eg. the two tile tall office block (4587), simply don't have a snowy alternate ground sprite. Because all of that concrete must be snow free, my stylistic decision was to have snowless concrete and snowy grass, to give some degree of visual consistency.

This would be fixable in an "OpenGFX2+ Houses" NewGRF, but that's not a high priority...

More/better snow on roads is related to #102
